require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });
const {
  sequelize, User, CircuitDesign, ErrorCorrection, AlgorithmOptimization,
  QubitManagement, GateOperation, QuantumSimulation, NoiseAnalysis,
  StateVisualization, EntanglementAnalysis, QuantumML, ResearchPaper,
  QuantumProtocol, HardwareProfile, BenchmarkTest, LearningResource
} = require('../models');

async function seed() {
  try {
    if (process.env.ALLOW_DESTRUCTIVE_SEED !== '1') throw new Error('Set ALLOW_DESTRUCTIVE_SEED=1 only for an isolated demo database');
    if ((process.env.SEED_ADMIN_PASSWORD || '').length < 12) throw new Error('SEED_ADMIN_PASSWORD must contain at least 12 characters');
    await sequelize.sync({ force: true });
    console.log('Database synced (tables dropped and recreated).');

    // ── User ──
    await User.create({
      email: process.env.DEFAULT_EMAIL || 'admin@quantum.ai',
      password: process.env.SEED_ADMIN_PASSWORD,
      name: 'Dr. Quantum Admin',
      role: 'admin'
    });
    console.log('Default user created.');

    // ── 1. Circuit Designs (15) ──
    await CircuitDesign.bulkCreate([
      { name: 'Bell State Preparation', description: 'Creates maximally entangled Bell state |Φ+⟩ using Hadamard and CNOT gates', qubitCount: 2, gateSequence: { gates: ['H', 'CNOT'] }, circuitDepth: 2, targetFidelity: 0.998, status: 'active', category: 'Entanglement', complexity: 'Low', estimatedRuntime: '10ns', tags: ['bell', 'entanglement', 'basic'] },
      { name: 'GHZ State Circuit', description: 'Greenberger-Horne-Zeilinger state for multi-qubit entanglement', qubitCount: 5, gateSequence: { gates: ['H', 'CNOT', 'CNOT', 'CNOT', 'CNOT'] }, circuitDepth: 5, targetFidelity: 0.985, status: 'active', category: 'Entanglement', complexity: 'Medium', estimatedRuntime: '50ns', tags: ['ghz', 'multipartite'] },
      { name: 'Quantum Fourier Transform', description: 'QFT circuit implementing discrete Fourier transform on quantum amplitudes', qubitCount: 8, gateSequence: { gates: ['H', 'CP', 'CP', 'SWAP'] }, circuitDepth: 28, targetFidelity: 0.95, status: 'active', category: 'Transform', complexity: 'High', estimatedRuntime: '280ns', tags: ['qft', 'transform', 'arithmetic'] },
      { name: "Grover's Search Oracle", description: "Oracle circuit for Grover's quantum search algorithm with 4-qubit database", qubitCount: 4, gateSequence: { gates: ['H', 'X', 'MCZ', 'X', 'H'] }, circuitDepth: 12, targetFidelity: 0.97, status: 'active', category: 'Search', complexity: 'Medium', estimatedRuntime: '120ns', tags: ['grover', 'search', 'oracle'] },
      { name: 'VQE Ansatz UCCSD', description: 'Unitary Coupled Cluster Singles and Doubles ansatz for variational quantum eigensolver', qubitCount: 8, gateSequence: { gates: ['RY', 'CNOT', 'RZ', 'CNOT'] }, circuitDepth: 45, targetFidelity: 0.92, status: 'experimental', category: 'Chemistry', complexity: 'Very High', estimatedRuntime: '450ns', tags: ['vqe', 'chemistry', 'variational'] },
      { name: 'QAOA MaxCut p=3', description: 'Quantum Approximate Optimization Algorithm for MaxCut graph problem', qubitCount: 10, gateSequence: { gates: ['H', 'RZZ', 'RX'] }, circuitDepth: 36, targetFidelity: 0.88, status: 'experimental', category: 'Optimization', complexity: 'High', estimatedRuntime: '360ns', tags: ['qaoa', 'optimization', 'maxcut'] },
      { name: 'Quantum Walk Circuit', description: 'Discrete-time quantum walk on a cycle graph with coin operator', qubitCount: 6, gateSequence: { gates: ['H', 'S', 'CNOT', 'SHIFT'] }, circuitDepth: 20, targetFidelity: 0.94, status: 'active', category: 'Walk', complexity: 'Medium', estimatedRuntime: '200ns', tags: ['walk', 'graph'] },
      { name: 'Quantum Teleportation', description: 'Standard quantum teleportation protocol using Bell pair and classical communication', qubitCount: 3, gateSequence: { gates: ['H', 'CNOT', 'CNOT', 'H', 'MEASURE', 'X', 'Z'] }, circuitDepth: 6, targetFidelity: 0.996, status: 'active', category: 'Communication', complexity: 'Low', estimatedRuntime: '60ns', tags: ['teleportation', 'communication'] },
      { name: 'Bernstein-Vazirani', description: 'Determines hidden bit string using single quantum query', qubitCount: 6, gateSequence: { gates: ['H', 'CNOT', 'H'] }, circuitDepth: 8, targetFidelity: 0.99, status: 'active', category: 'Algorithm', complexity: 'Low', estimatedRuntime: '80ns', tags: ['bernstein-vazirani', 'query'] },
      { name: "Simon's Algorithm", description: "Finds hidden period in a function with exponential quantum speedup", qubitCount: 8, gateSequence: { gates: ['H', 'ORACLE', 'H', 'MEASURE'] }, circuitDepth: 16, targetFidelity: 0.96, status: 'active', category: 'Algorithm', complexity: 'Medium', estimatedRuntime: '160ns', tags: ['simon', 'period-finding'] },
      { name: "Shor's Period Finding", description: "Period finding subroutine for Shor's factoring algorithm", qubitCount: 14, gateSequence: { gates: ['H', 'MOD_EXP', 'QFT_INV'] }, circuitDepth: 80, targetFidelity: 0.85, status: 'experimental', category: 'Cryptography', complexity: 'Very High', estimatedRuntime: '800ns', tags: ['shor', 'factoring', 'rsa'] },
      { name: 'Quantum Phase Estimation', description: 'Estimates eigenvalue phases of unitary operators with precision', qubitCount: 10, gateSequence: { gates: ['H', 'CU', 'QFT_INV'] }, circuitDepth: 50, targetFidelity: 0.93, status: 'active', category: 'Estimation', complexity: 'High', estimatedRuntime: '500ns', tags: ['phase-estimation', 'eigenvalue'] },
      { name: 'Toffoli Decomposition', description: 'Decomposed Toffoli (CCX) gate using single and two-qubit gates', qubitCount: 3, gateSequence: { gates: ['H', 'CNOT', 'T', 'T_DAG', 'CNOT', 'T', 'H'] }, circuitDepth: 15, targetFidelity: 0.99, status: 'active', category: 'Gate Synthesis', complexity: 'Medium', estimatedRuntime: '150ns', tags: ['toffoli', 'decomposition'] },
      { name: 'Fredkin Gate Circuit', description: 'Controlled-SWAP gate implementation for quantum routing', qubitCount: 3, gateSequence: { gates: ['CNOT', 'TOFFOLI', 'CNOT'] }, circuitDepth: 10, targetFidelity: 0.98, status: 'active', category: 'Gate Synthesis', complexity: 'Medium', estimatedRuntime: '100ns', tags: ['fredkin', 'cswap'] },
      { name: 'Deutsch-Jozsa Algorithm', description: 'Determines if function is constant or balanced in single query', qubitCount: 4, gateSequence: { gates: ['X', 'H', 'ORACLE', 'H', 'MEASURE'] }, circuitDepth: 6, targetFidelity: 0.997, status: 'active', category: 'Algorithm', complexity: 'Low', estimatedRuntime: '60ns', tags: ['deutsch-jozsa', 'decision'] },
    ]);
    console.log('Circuit Designs seeded.');

    // ── 2. Error Corrections (15) ──
    await ErrorCorrection.bulkCreate([
      { name: 'Surface Code d=3', description: 'Topological surface code with distance 3 for fault-tolerant quantum computing', codeType: 'Surface Code', errorRate: 0.001, correctionCapability: 'Single qubit X and Z errors', qubitOverhead: 17, syndromeExtraction: 'Stabilizer measurement', decoderType: 'MWPM', logicalErrorRate: 0.00001, status: 'active', category: 'Topological', tags: ['surface', 'fault-tolerant'] },
      { name: 'Steane [[7,1,3]] Code', description: 'CSS code encoding 1 logical qubit in 7 physical qubits', codeType: 'Steane Code', errorRate: 0.005, correctionCapability: 'Single qubit errors', qubitOverhead: 7, syndromeExtraction: 'Ancilla-based', decoderType: 'Lookup Table', logicalErrorRate: 0.00003, status: 'active', category: 'CSS', tags: ['steane', 'css'] },
      { name: 'Shor [[9,1,3]] Code', description: 'First quantum error correction code combining bit-flip and phase-flip codes', codeType: 'Shor Code', errorRate: 0.008, correctionCapability: 'Single arbitrary errors', qubitOverhead: 9, syndromeExtraction: 'Sequential measurement', decoderType: 'Majority Vote', logicalErrorRate: 0.00006, status: 'active', category: 'Concatenated', tags: ['shor', 'pioneering'] },
      { name: 'Bacon-Shor Code', description: 'Subsystem code with simplified syndrome extraction', codeType: 'Bacon-Shor', errorRate: 0.003, correctionCapability: 'Single qubit errors with gauge fixing', qubitOverhead: 9, syndromeExtraction: 'Gauge measurement', decoderType: 'Minimum Weight', logicalErrorRate: 0.00002, status: 'active', category: 'Subsystem', tags: ['bacon-shor', 'subsystem'] },
      { name: 'Color Code 4.8.8', description: 'Color code on 4.8.8 lattice supporting transversal non-Clifford gates', codeType: 'Color Code', errorRate: 0.002, correctionCapability: 'Distance-3 errors', qubitOverhead: 18, syndromeExtraction: 'Face measurement', decoderType: 'Restriction Decoder', logicalErrorRate: 0.00001, status: 'experimental', category: 'Topological', tags: ['color', 'transversal'] },
      { name: 'Toric Code', description: 'Kitaev toric code on periodic boundary conditions', codeType: 'Toric Code', errorRate: 0.001, correctionCapability: 'Topological protection', qubitOverhead: 32, syndromeExtraction: 'Plaquette and vertex operators', decoderType: 'MWPM', logicalErrorRate: 0.000005, status: 'active', category: 'Topological', tags: ['toric', 'kitaev'] },
      { name: 'Repetition Code d=5', description: 'Simple repetition code for single error type correction', codeType: 'Repetition Code', errorRate: 0.01, correctionCapability: 'Up to 2 bit-flip errors', qubitOverhead: 5, syndromeExtraction: 'Parity check', decoderType: 'Majority Vote', logicalErrorRate: 0.0001, status: 'active', category: 'Classical-inspired', tags: ['repetition', 'basic'] },
      { name: 'Kitaev Honeycomb Code', description: 'Honeycomb lattice code based on Kitaev model', codeType: 'Kitaev Code', errorRate: 0.002, correctionCapability: 'Anyonic error correction', qubitOverhead: 24, syndromeExtraction: 'Anyon detection', decoderType: 'Fusion-based', logicalErrorRate: 0.00001, status: 'experimental', category: 'Topological', tags: ['kitaev', 'honeycomb'] },
      { name: 'Reed-Muller [[15,1,3]]', description: 'Quantum Reed-Muller code supporting transversal T gate', codeType: 'Reed-Muller', errorRate: 0.004, correctionCapability: 'Single qubit errors', qubitOverhead: 15, syndromeExtraction: 'Stabilizer measurement', decoderType: 'Lookup Table', logicalErrorRate: 0.00002, status: 'active', category: 'CSS', tags: ['reed-muller', 'transversal-t'] },
      { name: 'Quantum Golay [[23,1,7]]', description: 'High-distance Golay code for superior error correction', codeType: 'Golay Code', errorRate: 0.006, correctionCapability: 'Up to 3 qubit errors', qubitOverhead: 23, syndromeExtraction: 'Stabilizer measurement', decoderType: 'Syndrome Table', logicalErrorRate: 0.0000001, status: 'experimental', category: 'CSS', tags: ['golay', 'high-distance'] },
      { name: 'Quantum LDPC Code', description: 'Low-density parity-check quantum code with efficient encoding', codeType: 'LDPC', errorRate: 0.003, correctionCapability: 'Multiple error correction', qubitOverhead: 50, syndromeExtraction: 'Sparse parity check', decoderType: 'Belief Propagation', logicalErrorRate: 0.00001, status: 'experimental', category: 'Graph-based', tags: ['ldpc', 'efficient'] },
      { name: 'Topological Color Code 3D', description: '3D color code enabling universal transversal gate set', codeType: 'Topological', errorRate: 0.001, correctionCapability: 'Multi-dimensional protection', qubitOverhead: 100, syndromeExtraction: 'Cell measurement', decoderType: 'Sweep Decoder', logicalErrorRate: 0.0000001, status: 'experimental', category: 'Topological', tags: ['3d', 'universal'] },
      { name: 'Concatenated Steane Code', description: 'Two-level concatenation of Steane code for lower logical error', codeType: 'Concatenated', errorRate: 0.004, correctionCapability: 'Multi-level error correction', qubitOverhead: 49, syndromeExtraction: 'Hierarchical', decoderType: 'Recursive', logicalErrorRate: 0.0000001, status: 'active', category: 'Concatenated', tags: ['concatenated', 'hierarchical'] },
      { name: 'Floquet Code', description: 'Dynamically generated topological code using periodic measurements', codeType: 'Floquet', errorRate: 0.002, correctionCapability: 'Dynamical error correction', qubitOverhead: 12, syndromeExtraction: 'Periodic measurement', decoderType: 'Matching', logicalErrorRate: 0.00002, status: 'experimental', category: 'Dynamic', tags: ['floquet', 'dynamic'] },
      { name: 'Subsystem Surface Code', description: 'Subsystem variant of surface code with reduced weight stabilizers', codeType: 'Subsystem', errorRate: 0.002, correctionCapability: 'Single qubit errors', qubitOverhead: 20, syndromeExtraction: 'Weight-2 gauge ops', decoderType: 'MWPM', logicalErrorRate: 0.00001, status: 'active', category: 'Subsystem', tags: ['subsystem', 'surface'] },
    ]);
    console.log('Error Corrections seeded.');

    // ── 3. Algorithm Optimizations (15) ──
    await AlgorithmOptimization.bulkCreate([
      { name: "Shor's Factoring Optimized", description: 'Optimized implementation of Shor\'s algorithm with reduced T-gate count', algorithmType: 'Factoring', originalComplexity: 'O(n^3)', optimizedComplexity: 'O(n^2 log n)', speedup: 'Exponential over classical', qubitRequirement: 2048, gateCount: 500000, applicationDomain: 'Cryptography', status: 'active', category: 'Number Theory', tags: ['shor', 'factoring'] },
      { name: "Grover's Search Amplitude", description: 'Amplitude amplification variant of Grover search with fixed-point', algorithmType: 'Search', originalComplexity: 'O(N)', optimizedComplexity: 'O(sqrt(N))', speedup: 'Quadratic', qubitRequirement: 20, gateCount: 1200, applicationDomain: 'Database Search', status: 'active', category: 'Search', tags: ['grover', 'amplitude'] },
      { name: 'HHL Linear Systems', description: 'Harrow-Hassidim-Lloyd algorithm for solving linear systems', algorithmType: 'Linear Algebra', originalComplexity: 'O(N^3)', optimizedComplexity: 'O(poly(log N))', speedup: 'Exponential', qubitRequirement: 100, gateCount: 50000, applicationDomain: 'Scientific Computing', status: 'experimental', category: 'Linear Algebra', tags: ['hhl', 'linear-systems'] },
      { name: 'QAOA MaxCut Optimized', description: 'Improved QAOA with parameter concentration for MaxCut', algorithmType: 'Optimization', originalComplexity: 'O(2^n)', optimizedComplexity: 'O(p*n)', speedup: 'Polynomial approximation', qubitRequirement: 50, gateCount: 3000, applicationDomain: 'Combinatorial Optimization', status: 'active', category: 'Optimization', tags: ['qaoa', 'maxcut'] },
      { name: 'VQE Molecular Ground State', description: 'Variational quantum eigensolver with hardware-efficient ansatz', algorithmType: 'Chemistry', originalComplexity: 'O(N^7) FCI', optimizedComplexity: 'O(N^4) VQE', speedup: 'Cubic improvement', qubitRequirement: 16, gateCount: 5000, applicationDomain: 'Quantum Chemistry', status: 'active', category: 'Chemistry', tags: ['vqe', 'chemistry'] },
      { name: 'Quantum Walk Search', description: 'Spatial quantum walk-based search algorithm on graphs', algorithmType: 'Walk', originalComplexity: 'O(N)', optimizedComplexity: 'O(sqrt(N))', speedup: 'Quadratic', qubitRequirement: 12, gateCount: 800, applicationDomain: 'Graph Analysis', status: 'active', category: 'Graph', tags: ['walk', 'graph'] },
      { name: 'Iterative Phase Estimation', description: 'Resource-efficient iterative QPE using single ancilla qubit', algorithmType: 'Estimation', originalComplexity: 'O(n) qubits', optimizedComplexity: 'O(1) ancilla', speedup: 'n-fold qubit reduction', qubitRequirement: 5, gateCount: 2000, applicationDomain: 'Spectroscopy', status: 'active', category: 'Estimation', tags: ['ipe', 'resource-efficient'] },
      { name: 'Quantum Amplitude Estimation', description: 'Maximum likelihood amplitude estimation without QPE', algorithmType: 'Estimation', originalComplexity: 'O(1/eps^2)', optimizedComplexity: 'O(1/eps)', speedup: 'Quadratic', qubitRequirement: 8, gateCount: 1500, applicationDomain: 'Finance', status: 'active', category: 'Finance', tags: ['amplitude', 'monte-carlo'] },
      { name: 'Quantum Counting', description: 'Combines Grover and QPE for counting solutions', algorithmType: 'Counting', originalComplexity: 'O(N)', optimizedComplexity: 'O(sqrt(N))', speedup: 'Quadratic', qubitRequirement: 10, gateCount: 900, applicationDomain: 'Satisfiability', status: 'active', category: 'Search', tags: ['counting', 'sat'] },
      { name: "Simon's Problem Optimized", description: "Optimized circuit for Simon's hidden subgroup problem", algorithmType: 'Hidden Subgroup', originalComplexity: 'O(2^(n/2))', optimizedComplexity: 'O(n)', speedup: 'Exponential', qubitRequirement: 12, gateCount: 600, applicationDomain: 'Cryptanalysis', status: 'active', category: 'Algebra', tags: ['simon', 'subgroup'] },
      { name: 'Bernstein-Vazirani Extended', description: 'Multi-query extension of BV algorithm for recursive structures', algorithmType: 'Query', originalComplexity: 'O(n)', optimizedComplexity: 'O(1)', speedup: 'Linear to constant', qubitRequirement: 8, gateCount: 200, applicationDomain: 'Oracle Problems', status: 'active', category: 'Query', tags: ['bv', 'recursive'] },
      { name: 'Deutsch-Jozsa Generalized', description: 'Generalized DJ algorithm for multi-valued functions', algorithmType: 'Decision', originalComplexity: 'O(2^(n-1)+1)', optimizedComplexity: 'O(1)', speedup: 'Exponential', qubitRequirement: 6, gateCount: 150, applicationDomain: 'Function Analysis', status: 'active', category: 'Decision', tags: ['deutsch-jozsa'] },
      { name: 'Hamiltonian Simulation Trotter', description: 'Product formula approach for quantum Hamiltonian simulation', algorithmType: 'Simulation', originalComplexity: 'O(t^2/eps)', optimizedComplexity: 'O(t*polylog(t/eps))', speedup: 'Near-linear in time', qubitRequirement: 30, gateCount: 100000, applicationDomain: 'Physics Simulation', status: 'active', category: 'Simulation', tags: ['trotter', 'hamiltonian'] },
      { name: 'Quantum Annealing Schedule', description: 'Optimized annealing schedule for combinatorial optimization', algorithmType: 'Annealing', originalComplexity: 'O(2^n)', optimizedComplexity: 'O(poly(n)) heuristic', speedup: 'Heuristic speedup', qubitRequirement: 200, gateCount: 0, applicationDomain: 'Logistics', status: 'experimental', category: 'Annealing', tags: ['annealing', 'scheduling'] },
      { name: 'Quantum Approximate Counting', description: 'Approximate counting using amplitude estimation techniques', algorithmType: 'Counting', originalComplexity: 'O(N/eps^2)', optimizedComplexity: 'O(sqrt(N)/eps)', speedup: 'Quadratic', qubitRequirement: 12, gateCount: 1800, applicationDomain: 'Statistics', status: 'active', category: 'Statistics', tags: ['counting', 'approximate'] },
    ]);
    console.log('Algorithm Optimizations seeded.');

    // ── 4. Qubit Managements (15) ──
    await QubitManagement.bulkCreate([
      { name: 'Superconducting Transmon Q1', description: 'IBM-style transmon qubit with fixed-frequency design', qubitType: 'Transmon', coherenceTime: '100 us', gateTime: '30 ns', connectivity: 'Heavy-hex lattice', errorRate: 0.001, temperature: '15 mK', calibrationStatus: 'Calibrated', status: 'active', category: 'Superconducting', tags: ['transmon', 'ibm'] },
      { name: 'Ion Trap Ytterbium-171', description: 'Trapped Yb-171 ion qubit with all-to-all connectivity', qubitType: 'Ion Trap', coherenceTime: '10 s', gateTime: '200 us', connectivity: 'All-to-all', errorRate: 0.0005, temperature: '10 uK', calibrationStatus: 'Calibrated', status: 'active', category: 'Trapped Ion', tags: ['ion-trap', 'ytterbium'] },
      { name: 'Photonic Squeezed State', description: 'Gaussian boson sampling photonic qubit', qubitType: 'Photonic', coherenceTime: 'N/A (ballistic)', gateTime: '1 ps', connectivity: 'Programmable interferometer', errorRate: 0.01, temperature: 'Room temperature', calibrationStatus: 'Aligned', status: 'active', category: 'Photonic', tags: ['photonic', 'boson'] },
      { name: 'Topological Majorana Zero Mode', description: 'Theoretical Majorana-based topological qubit', qubitType: 'Topological', coherenceTime: '> 1 s (theoretical)', gateTime: '100 ns', connectivity: 'Braiding network', errorRate: 0.0001, temperature: '20 mK', calibrationStatus: 'Research phase', status: 'experimental', category: 'Topological', tags: ['majorana', 'topological'] },
      { name: 'NV Center Diamond', description: 'Nitrogen-vacancy center in diamond at room temperature', qubitType: 'NV Center', coherenceTime: '1 ms', gateTime: '10 ns', connectivity: 'Optical interconnect', errorRate: 0.005, temperature: '300 K', calibrationStatus: 'Calibrated', status: 'active', category: 'Solid State', tags: ['nv-center', 'diamond'] },
      { name: 'Neutral Atom Rubidium-87', description: 'Optically trapped Rb-87 neutral atom qubit', qubitType: 'Neutral Atom', coherenceTime: '5 s', gateTime: '1 us', connectivity: 'Reconfigurable array', errorRate: 0.003, temperature: '10 uK', calibrationStatus: 'Calibrated', status: 'active', category: 'Neutral Atom', tags: ['neutral-atom', 'rubidium'] },
      { name: 'Silicon Spin Qubit', description: 'Electron spin qubit in silicon quantum dot', qubitType: 'Spin Qubit', coherenceTime: '30 ms', gateTime: '100 ns', connectivity: 'Linear nearest-neighbor', errorRate: 0.002, temperature: '100 mK', calibrationStatus: 'Calibrated', status: 'active', category: 'Semiconductor', tags: ['silicon', 'spin'] },
      { name: 'Flux Qubit', description: 'Persistent current flux qubit for quantum annealing', qubitType: 'Flux Qubit', coherenceTime: '50 us', gateTime: '50 ns', connectivity: 'Galvanic coupling', errorRate: 0.003, temperature: '15 mK', calibrationStatus: 'Calibrated', status: 'active', category: 'Superconducting', tags: ['flux', 'annealing'] },
      { name: 'Phase Qubit', description: 'Current-biased Josephson junction phase qubit', qubitType: 'Phase Qubit', coherenceTime: '5 us', gateTime: '20 ns', connectivity: 'Capacitive coupling', errorRate: 0.008, temperature: '20 mK', calibrationStatus: 'Calibrated', status: 'active', category: 'Superconducting', tags: ['phase', 'josephson'] },
      { name: 'Charge Qubit (Cooper Pair Box)', description: 'Original superconducting charge qubit design', qubitType: 'Charge Qubit', coherenceTime: '2 us', gateTime: '10 ns', connectivity: 'Capacitive', errorRate: 0.01, temperature: '20 mK', calibrationStatus: 'Calibrated', status: 'active', category: 'Superconducting', tags: ['charge', 'cooper-pair'] },
      { name: 'Cat Qubit (Kerr)', description: 'Bosonic cat qubit using Kerr nonlinearity for error protection', qubitType: 'Cat Qubit', coherenceTime: '200 us', gateTime: '500 ns', connectivity: 'Cavity bus', errorRate: 0.002, temperature: '15 mK', calibrationStatus: 'Experimental', status: 'experimental', category: 'Bosonic', tags: ['cat', 'bosonic'] },
      { name: 'Fluxonium Qubit', description: 'High-coherence fluxonium with large anharmonicity', qubitType: 'Fluxonium', coherenceTime: '500 us', gateTime: '60 ns', connectivity: 'Inductive coupling', errorRate: 0.0008, temperature: '15 mK', calibrationStatus: 'Calibrated', status: 'active', category: 'Superconducting', tags: ['fluxonium', 'high-coherence'] },
      { name: 'Gatemon (InAs Nanowire)', description: 'Semiconductor-superconductor hybrid gatemon qubit', qubitType: 'Gatemon', coherenceTime: '20 us', gateTime: '40 ns', connectivity: 'Capacitive', errorRate: 0.005, temperature: '20 mK', calibrationStatus: 'Calibrated', status: 'experimental', category: 'Hybrid', tags: ['gatemon', 'hybrid'] },
      { name: 'Andreev Level Qubit', description: 'Qubit based on Andreev bound states in Josephson junctions', qubitType: 'Andreev Qubit', coherenceTime: '10 us', gateTime: '30 ns', connectivity: 'Direct coupling', errorRate: 0.006, temperature: '15 mK', calibrationStatus: 'Research phase', status: 'experimental', category: 'Superconducting', tags: ['andreev', 'junction'] },
      { name: 'Phosphorus Donor Spin', description: 'P-31 donor spin qubit in isotopically pure Si-28', qubitType: 'Donor Spin', coherenceTime: '30 s', gateTime: '1 us', connectivity: 'Exchange coupling', errorRate: 0.003, temperature: '100 mK', calibrationStatus: 'Calibrated', status: 'active', category: 'Semiconductor', tags: ['phosphorus', 'donor'] },
    ]);
    console.log('Qubit Managements seeded.');

    // ── 5. Gate Operations (15) ──
    await GateOperation.bulkCreate([
      { name: 'Hadamard (H)', description: 'Creates equal superposition from computational basis states', gateType: 'Single-qubit', matrixRepresentation: { matrix: [[0.707, 0.707], [0.707, -0.707]] }, qubitCount: 1, fidelity: 0.9995, executionTime: '20 ns', decomposition: 'Rz(pi)Ry(pi/2)', isUniversal: false, status: 'active', category: 'Clifford', tags: ['hadamard', 'superposition'] },
      { name: 'CNOT (CX)', description: 'Controlled-NOT gate, fundamental two-qubit entangling gate', gateType: 'Two-qubit', matrixRepresentation: { matrix: [[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]] }, qubitCount: 2, fidelity: 0.995, executionTime: '300 ns', decomposition: 'Native', isUniversal: false, status: 'active', category: 'Clifford', tags: ['cnot', 'entangling'] },
      { name: 'Pauli-X', description: 'Quantum NOT gate, bit-flip operation', gateType: 'Single-qubit', matrixRepresentation: { matrix: [[0,1],[1,0]] }, qubitCount: 1, fidelity: 0.9998, executionTime: '15 ns', decomposition: 'Native', isUniversal: false, status: 'active', category: 'Pauli', tags: ['pauli-x', 'bit-flip'] },
      { name: 'Pauli-Y', description: 'Combined bit and phase flip operation', gateType: 'Single-qubit', matrixRepresentation: { matrix: [[0, '-i'],['i', 0]] }, qubitCount: 1, fidelity: 0.9997, executionTime: '15 ns', decomposition: 'XZ', isUniversal: false, status: 'active', category: 'Pauli', tags: ['pauli-y'] },
      { name: 'Pauli-Z', description: 'Phase-flip gate, leaves |0> unchanged and flips |1> phase', gateType: 'Single-qubit', matrixRepresentation: { matrix: [[1,0],[0,-1]] }, qubitCount: 1, fidelity: 0.9999, executionTime: '0 ns (virtual)', decomposition: 'Frame change', isUniversal: false, status: 'active', category: 'Pauli', tags: ['pauli-z', 'phase'] },
      { name: 'Phase Gate (S)', description: 'pi/2 phase rotation gate, square root of Z', gateType: 'Single-qubit', matrixRepresentation: { matrix: [[1,0],[0,'i']] }, qubitCount: 1, fidelity: 0.9998, executionTime: '0 ns (virtual)', decomposition: 'Rz(pi/2)', isUniversal: false, status: 'active', category: 'Clifford', tags: ['phase', 's-gate'] },
      { name: 'T Gate', description: 'pi/4 phase gate, essential for universality with Clifford+T', gateType: 'Single-qubit', matrixRepresentation: { matrix: [[1,0],[0,'exp(i*pi/4)']] }, qubitCount: 1, fidelity: 0.9996, executionTime: '0 ns (virtual)', decomposition: 'Rz(pi/4)', isUniversal: false, status: 'active', category: 'Non-Clifford', tags: ['t-gate', 'magic'] },
      { name: 'SWAP', description: 'Swaps the states of two qubits', gateType: 'Two-qubit', matrixRepresentation: { matrix: [[1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]] }, qubitCount: 2, fidelity: 0.993, executionTime: '900 ns', decomposition: '3 x CNOT', isUniversal: false, status: 'active', category: 'Permutation', tags: ['swap'] },
      { name: 'Toffoli (CCX)', description: 'Controlled-controlled-NOT, universal for classical computation', gateType: 'Three-qubit', matrixRepresentation: { matrix: 'Identity with (6,7) and (7,6) swapped' }, qubitCount: 3, fidelity: 0.98, executionTime: '4500 ns', decomposition: '6 CNOT + 9 single-qubit', isUniversal: true, status: 'active', category: 'Multi-qubit', tags: ['toffoli', 'classical-universal'] },
      { name: 'Fredkin (CSWAP)', description: 'Controlled-SWAP gate for quantum routing', gateType: 'Three-qubit', matrixRepresentation: { matrix: 'CSWAP matrix' }, qubitCount: 3, fidelity: 0.97, executionTime: '5000 ns', decomposition: '2 CNOT + 1 Toffoli', isUniversal: true, status: 'active', category: 'Multi-qubit', tags: ['fredkin', 'routing'] },
      { name: 'Rx(theta)', description: 'Rotation around X-axis by arbitrary angle theta', gateType: 'Parametric', matrixRepresentation: { matrix: 'cos(t/2)I - i*sin(t/2)X' }, qubitCount: 1, fidelity: 0.999, executionTime: '25 ns', decomposition: 'Native', isUniversal: false, status: 'active', category: 'Rotation', tags: ['rx', 'parametric'] },
      { name: 'Ry(theta)', description: 'Rotation around Y-axis by arbitrary angle theta', gateType: 'Parametric', matrixRepresentation: { matrix: 'cos(t/2)I - i*sin(t/2)Y' }, qubitCount: 1, fidelity: 0.999, executionTime: '25 ns', decomposition: 'Native', isUniversal: false, status: 'active', category: 'Rotation', tags: ['ry', 'parametric'] },
      { name: 'Rz(theta)', description: 'Rotation around Z-axis by arbitrary angle theta', gateType: 'Parametric', matrixRepresentation: { matrix: 'exp(-i*t/2)|0><0| + exp(i*t/2)|1><1|' }, qubitCount: 1, fidelity: 0.9999, executionTime: '0 ns (virtual)', decomposition: 'Frame change', isUniversal: false, status: 'active', category: 'Rotation', tags: ['rz', 'virtual'] },
      { name: 'CZ (Controlled-Z)', description: 'Controlled phase-flip gate, symmetric entangling gate', gateType: 'Two-qubit', matrixRepresentation: { matrix: [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,-1]] }, qubitCount: 2, fidelity: 0.996, executionTime: '250 ns', decomposition: 'Native on some hardware', isUniversal: false, status: 'active', category: 'Entangling', tags: ['cz', 'controlled'] },
      { name: 'iSWAP', description: 'Imaginary SWAP gate native to some superconducting architectures', gateType: 'Two-qubit', matrixRepresentation: { matrix: [[1,0,0,0],[0,0,'i',0],[0,'i',0,0],[0,0,0,1]] }, qubitCount: 2, fidelity: 0.994, executionTime: '200 ns', decomposition: 'Native on Google', isUniversal: false, status: 'active', category: 'Entangling', tags: ['iswap', 'google'] },
    ]);
    console.log('Gate Operations seeded.');

    // ── 6. Quantum Simulations (15) ──
    await QuantumSimulation.bulkCreate([
      { name: 'Transverse Ising Model 1D', description: 'Simulation of 1D transverse-field Ising model phase transition', simulationType: 'Hamiltonian', systemSize: 20, hamiltonianType: 'Ising', timeSteps: 1000, accuracy: 0.99, method: 'Trotterization', memoryUsage: '2 GB', status: 'completed', category: 'Condensed Matter', tags: ['ising', 'phase-transition'] },
      { name: 'Heisenberg XXZ Chain', description: 'Anti-ferromagnetic Heisenberg XXZ spin chain dynamics', simulationType: 'Hamiltonian', systemSize: 16, hamiltonianType: 'Heisenberg', timeSteps: 500, accuracy: 0.98, method: 'TEBD', memoryUsage: '4 GB', status: 'active', category: 'Magnetism', tags: ['heisenberg', 'spin-chain'] },
      { name: 'Hubbard Model 2D', description: '2D Fermi-Hubbard model for high-Tc superconductivity study', simulationType: 'Variational', systemSize: 12, hamiltonianType: 'Hubbard', timeSteps: 200, accuracy: 0.95, method: 'VQE', memoryUsage: '8 GB', status: 'running', category: 'Superconductivity', tags: ['hubbard', 'superconductor'] },
      { name: 'Fermi-Hubbard Half-filling', description: 'Fermi-Hubbard at half-filling exploring Mott insulator transition', simulationType: 'Ground State', systemSize: 8, hamiltonianType: 'Fermi-Hubbard', timeSteps: 300, accuracy: 0.97, method: 'DMRG-inspired', memoryUsage: '6 GB', status: 'active', category: 'Strongly Correlated', tags: ['mott', 'transition'] },
      { name: 'Bose-Hubbard Superfluid', description: 'Bose-Hubbard model simulation of superfluid-Mott insulator transition', simulationType: 'Phase Diagram', systemSize: 10, hamiltonianType: 'Bose-Hubbard', timeSteps: 400, accuracy: 0.96, method: 'Quantum Monte Carlo', memoryUsage: '3 GB', status: 'completed', category: 'Cold Atoms', tags: ['bose-hubbard', 'superfluid'] },
      { name: 'Molecular Hydrogen H2', description: 'Full configuration interaction simulation of H2 molecule', simulationType: 'Chemistry', systemSize: 4, hamiltonianType: 'Molecular', timeSteps: 100, accuracy: 0.999, method: 'Exact Diagonalization', memoryUsage: '256 MB', status: 'completed', category: 'Chemistry', tags: ['h2', 'molecular'] },
      { name: 'Lithium Hydride LiH', description: 'VQE simulation of LiH ground state energy surface', simulationType: 'Chemistry', systemSize: 12, hamiltonianType: 'Molecular', timeSteps: 150, accuracy: 0.98, method: 'VQE-UCCSD', memoryUsage: '1 GB', status: 'completed', category: 'Chemistry', tags: ['lih', 'energy-surface'] },
      { name: 'Water Molecule H2O', description: 'Quantum simulation of water molecule electronic structure', simulationType: 'Chemistry', systemSize: 14, hamiltonianType: 'Molecular', timeSteps: 200, accuracy: 0.96, method: 'ADAPT-VQE', memoryUsage: '4 GB', status: 'active', category: 'Chemistry', tags: ['water', 'electronic'] },
      { name: 'Nitrogen Fixation Catalyst', description: 'Simulation of FeMo-cofactor in nitrogenase for nitrogen fixation', simulationType: 'Chemistry', systemSize: 54, hamiltonianType: 'Molecular', timeSteps: 50, accuracy: 0.90, method: 'QPE', memoryUsage: '128 GB', status: 'experimental', category: 'Catalysis', tags: ['nitrogen', 'catalyst'] },
      { name: 'Lattice Gauge Theory U(1)', description: 'U(1) lattice gauge theory simulation for QED', simulationType: 'Field Theory', systemSize: 8, hamiltonianType: 'Gauge', timeSteps: 500, accuracy: 0.94, method: 'Trotterization', memoryUsage: '16 GB', status: 'experimental', category: 'High Energy', tags: ['gauge', 'qed'] },
      { name: 'Schwinger Model 1+1D', description: 'Schwinger model for quantum electrodynamics in 1+1 dimensions', simulationType: 'Field Theory', systemSize: 12, hamiltonianType: 'Schwinger', timeSteps: 300, accuracy: 0.96, method: 'Variational', memoryUsage: '2 GB', status: 'active', category: 'High Energy', tags: ['schwinger', 'qed'] },
      { name: 'Higher-Order Trotterization', description: 'Fourth-order Trotter-Suzuki decomposition benchmark', simulationType: 'Method Benchmark', systemSize: 16, hamiltonianType: 'Generic', timeSteps: 1000, accuracy: 0.999, method: 'Trotter-Suzuki 4th', memoryUsage: '1 GB', status: 'completed', category: 'Methodology', tags: ['trotter', 'benchmark'] },
      { name: 'VQE Excited States', description: 'VQE extension for computing excited state energies', simulationType: 'Chemistry', systemSize: 8, hamiltonianType: 'Molecular', timeSteps: 200, accuracy: 0.95, method: 'qEOM-VQE', memoryUsage: '2 GB', status: 'active', category: 'Chemistry', tags: ['vqe', 'excited'] },
      { name: 'DMRG-Quantum Hybrid', description: 'Hybrid classical DMRG with quantum subspace expansion', simulationType: 'Hybrid', systemSize: 30, hamiltonianType: 'Spin Chain', timeSteps: 100, accuracy: 0.98, method: 'DMRG-QSE', memoryUsage: '32 GB', status: 'experimental', category: 'Hybrid Methods', tags: ['dmrg', 'hybrid'] },
      { name: 'Tensor Network Contraction', description: 'Quantum-inspired tensor network simulation of 2D systems', simulationType: 'Tensor Network', systemSize: 25, hamiltonianType: 'PEPS', timeSteps: 150, accuracy: 0.93, method: 'TEBD-2D', memoryUsage: '64 GB', status: 'active', category: 'Tensor Networks', tags: ['tensor', 'peps'] },
    ]);
    console.log('Quantum Simulations seeded.');

    // ── 7. Noise Analyses (15) ──
    await NoiseAnalysis.bulkCreate([
      { name: 'Depolarizing Channel Analysis', description: 'Symmetric depolarizing noise model for single-qubit gates', noiseModel: 'Depolarizing', depolarizingRate: 0.001, dampingRate: 0, dephazingRate: 0, measurementError: 0.01, mitigationStrategy: 'Zero Noise Extrapolation', fidelityImpact: 0.05, status: 'active', category: 'Gate Noise', tags: ['depolarizing', 'symmetric'] },
      { name: 'Amplitude Damping T1', description: 'Energy relaxation noise from T1 decay process', noiseModel: 'Amplitude Damping', depolarizingRate: 0, dampingRate: 0.005, dephazingRate: 0, measurementError: 0.01, mitigationStrategy: 'Dynamical Decoupling', fidelityImpact: 0.08, status: 'active', category: 'Decoherence', tags: ['t1', 'relaxation'] },
      { name: 'Phase Damping T2', description: 'Pure dephasing noise from T2 decoherence', noiseModel: 'Phase Damping', depolarizingRate: 0, dampingRate: 0, dephazingRate: 0.008, measurementError: 0.01, mitigationStrategy: 'Spin Echo', fidelityImpact: 0.06, status: 'active', category: 'Decoherence', tags: ['t2', 'dephasing'] },
      { name: 'Bit Flip Channel', description: 'Random bit-flip error affecting qubit states', noiseModel: 'Bit Flip', depolarizingRate: 0.002, dampingRate: 0, dephazingRate: 0, measurementError: 0.005, mitigationStrategy: 'Repetition Code', fidelityImpact: 0.03, status: 'active', category: 'Pauli Noise', tags: ['bit-flip', 'x-error'] },
      { name: 'Phase Flip Channel', description: 'Random phase-flip error on qubit states', noiseModel: 'Phase Flip', depolarizingRate: 0, dampingRate: 0, dephazingRate: 0.003, measurementError: 0.005, mitigationStrategy: 'Phase Code', fidelityImpact: 0.04, status: 'active', category: 'Pauli Noise', tags: ['phase-flip', 'z-error'] },
      { name: 'Bit-Phase Flip Channel', description: 'Combined bit and phase flip (Y-error) noise', noiseModel: 'Bit-Phase Flip', depolarizingRate: 0.001, dampingRate: 0, dephazingRate: 0.001, measurementError: 0.005, mitigationStrategy: 'Shor Code', fidelityImpact: 0.05, status: 'active', category: 'Pauli Noise', tags: ['y-error', 'combined'] },
      { name: 'Thermal Relaxation Model', description: 'Combined T1 and T2 relaxation with thermal population', noiseModel: 'Thermal Relaxation', depolarizingRate: 0.001, dampingRate: 0.003, dephazingRate: 0.005, measurementError: 0.015, mitigationStrategy: 'Post-selection', fidelityImpact: 0.12, status: 'active', category: 'Combined', tags: ['thermal', 'combined'] },
      { name: 'Crosstalk Analysis ZZ', description: 'ZZ crosstalk between neighboring qubits on chip', noiseModel: 'Crosstalk', depolarizingRate: 0, dampingRate: 0, dephazingRate: 0.002, measurementError: 0.01, mitigationStrategy: 'Dynamical Decoupling', fidelityImpact: 0.07, status: 'active', category: 'Correlated', tags: ['crosstalk', 'zz'] },
      { name: 'Leakage to Non-Computational', description: 'Population leakage outside the qubit computational subspace', noiseModel: 'Leakage', depolarizingRate: 0.0005, dampingRate: 0.001, dephazingRate: 0, measurementError: 0.02, mitigationStrategy: 'Leakage Reduction Units', fidelityImpact: 0.1, status: 'experimental', category: 'Leakage', tags: ['leakage', 'non-computational'] },
      { name: 'Readout Error Characterization', description: 'Measurement assignment error analysis', noiseModel: 'Readout Error', depolarizingRate: 0, dampingRate: 0, dephazingRate: 0, measurementError: 0.03, mitigationStrategy: 'M3 Mitigation', fidelityImpact: 0.03, status: 'active', category: 'Measurement', tags: ['readout', 'assignment'] },
      { name: 'Two-Qubit Gate Noise', description: 'Correlated noise during two-qubit CNOT operations', noiseModel: 'Gate Noise', depolarizingRate: 0.005, dampingRate: 0.001, dephazingRate: 0.002, measurementError: 0.01, mitigationStrategy: 'PEC', fidelityImpact: 0.15, status: 'active', category: 'Gate Noise', tags: ['two-qubit', 'cnot'] },
      { name: 'Correlated Dephasing', description: 'Spatially correlated dephasing noise across qubit register', noiseModel: 'Correlated', depolarizingRate: 0, dampingRate: 0, dephazingRate: 0.004, measurementError: 0.01, mitigationStrategy: 'Decoherence-Free Subspace', fidelityImpact: 0.09, status: 'experimental', category: 'Correlated', tags: ['correlated', 'spatial'] },
      { name: 'ZNE Benchmark Study', description: 'Zero Noise Extrapolation effectiveness benchmark', noiseModel: 'Depolarizing', depolarizingRate: 0.003, dampingRate: 0.001, dephazingRate: 0.002, measurementError: 0.015, mitigationStrategy: 'ZNE Richardson', fidelityImpact: 0.02, status: 'completed', category: 'Mitigation', tags: ['zne', 'benchmark'] },
      { name: 'PEC Cost Analysis', description: 'Probabilistic Error Cancellation sampling overhead study', noiseModel: 'Depolarizing', depolarizingRate: 0.002, dampingRate: 0.001, dephazingRate: 0.001, measurementError: 0.01, mitigationStrategy: 'PEC', fidelityImpact: 0.01, status: 'completed', category: 'Mitigation', tags: ['pec', 'sampling'] },
      { name: 'Randomized Compiling', description: 'Twirling technique to convert coherent errors to stochastic', noiseModel: 'Coherent', depolarizingRate: 0.001, dampingRate: 0, dephazingRate: 0.001, measurementError: 0.01, mitigationStrategy: 'Pauli Twirling', fidelityImpact: 0.04, status: 'active', category: 'Compilation', tags: ['twirling', 'randomized'] },
    ]);
    console.log('Noise Analyses seeded.');

    // ── 8. State Visualizations (15) ──
    await StateVisualization.bulkCreate([
      { name: '|0> Ground State', description: 'Computational basis ground state on Bloch sphere north pole', stateType: 'Pure', qubitCount: 1, blochCoordinates: { theta: 0, phi: 0, x: 0, y: 0, z: 1 }, densityMatrix: { rho: [[1,0],[0,0]] }, purity: 1.0, entropy: 0, visualizationType: 'Bloch Sphere', status: 'active', category: 'Basis', tags: ['ground', 'pure'] },
      { name: '|1> Excited State', description: 'Computational basis excited state on Bloch sphere south pole', stateType: 'Pure', qubitCount: 1, blochCoordinates: { theta: 3.14159, phi: 0, x: 0, y: 0, z: -1 }, densityMatrix: { rho: [[0,0],[0,1]] }, purity: 1.0, entropy: 0, visualizationType: 'Bloch Sphere', status: 'active', category: 'Basis', tags: ['excited', 'pure'] },
      { name: '|+> Superposition', description: 'Equal superposition state on Bloch sphere equator (+x)', stateType: 'Pure', qubitCount: 1, blochCoordinates: { theta: 1.5708, phi: 0, x: 1, y: 0, z: 0 }, densityMatrix: { rho: [[0.5, 0.5],[0.5, 0.5]] }, purity: 1.0, entropy: 0, visualizationType: 'Bloch Sphere', status: 'active', category: 'Superposition', tags: ['plus', 'hadamard'] },
      { name: '|-> Superposition', description: 'Minus superposition state on Bloch sphere equator (-x)', stateType: 'Pure', qubitCount: 1, blochCoordinates: { theta: 1.5708, phi: 3.14159, x: -1, y: 0, z: 0 }, densityMatrix: { rho: [[0.5, -0.5],[-0.5, 0.5]] }, purity: 1.0, entropy: 0, visualizationType: 'Bloch Sphere', status: 'active', category: 'Superposition', tags: ['minus'] },
      { name: 'Bell |Phi+>', description: 'Maximally entangled Bell state (|00> + |11>)/sqrt(2)', stateType: 'Entangled', qubitCount: 2, blochCoordinates: { note: 'Cannot be represented on single Bloch sphere' }, densityMatrix: { rho: [[0.5,0,0,0.5],[0,0,0,0],[0,0,0,0],[0.5,0,0,0.5]] }, purity: 1.0, entropy: 1.0, visualizationType: 'Density Matrix', status: 'active', category: 'Bell State', tags: ['bell', 'phi-plus'] },
      { name: 'Bell |Phi->', description: 'Bell state (|00> - |11>)/sqrt(2)', stateType: 'Entangled', qubitCount: 2, blochCoordinates: null, densityMatrix: { rho: [[0.5,0,0,-0.5],[0,0,0,0],[0,0,0,0],[-0.5,0,0,0.5]] }, purity: 1.0, entropy: 1.0, visualizationType: 'Density Matrix', status: 'active', category: 'Bell State', tags: ['bell', 'phi-minus'] },
      { name: 'Bell |Psi+>', description: 'Bell state (|01> + |10>)/sqrt(2)', stateType: 'Entangled', qubitCount: 2, blochCoordinates: null, densityMatrix: { rho: [[0,0,0,0],[0,0.5,0.5,0],[0,0.5,0.5,0],[0,0,0,0]] }, purity: 1.0, entropy: 1.0, visualizationType: 'Density Matrix', status: 'active', category: 'Bell State', tags: ['bell', 'psi-plus'] },
      { name: 'Bell |Psi->', description: 'Singlet Bell state (|01> - |10>)/sqrt(2)', stateType: 'Entangled', qubitCount: 2, blochCoordinates: null, densityMatrix: { rho: [[0,0,0,0],[0,0.5,-0.5,0],[0,-0.5,0.5,0],[0,0,0,0]] }, purity: 1.0, entropy: 1.0, visualizationType: 'Density Matrix', status: 'active', category: 'Bell State', tags: ['bell', 'singlet'] },
      { name: 'GHZ State 3-qubit', description: '(|000> + |111>)/sqrt(2) three-qubit GHZ state', stateType: 'Entangled', qubitCount: 3, blochCoordinates: null, densityMatrix: { note: '8x8 density matrix' }, purity: 1.0, entropy: 1.0, visualizationType: 'Q-Sphere', status: 'active', category: 'Multipartite', tags: ['ghz', 'three-qubit'] },
      { name: 'W State 3-qubit', description: '(|001> + |010> + |100>)/sqrt(3) three-qubit W state', stateType: 'Entangled', qubitCount: 3, blochCoordinates: null, densityMatrix: { note: '8x8 density matrix' }, purity: 1.0, entropy: 0.918, visualizationType: 'Q-Sphere', status: 'active', category: 'Multipartite', tags: ['w-state'] },
      { name: 'Cat State', description: 'Schrodinger cat state superposition of coherent states', stateType: 'Bosonic', qubitCount: 1, blochCoordinates: null, densityMatrix: { note: 'Infinite-dimensional' }, purity: 1.0, entropy: 0, visualizationType: 'Wigner Function', status: 'experimental', category: 'Bosonic', tags: ['cat', 'coherent'] },
      { name: 'Thermal Mixed State', description: 'Mixed state at finite temperature T', stateType: 'Mixed', qubitCount: 1, blochCoordinates: { theta: 0, phi: 0, x: 0, y: 0, z: 0.5 }, densityMatrix: { rho: [[0.75, 0],[0, 0.25]] }, purity: 0.625, entropy: 0.811, visualizationType: 'Bloch Sphere', status: 'active', category: 'Thermal', tags: ['mixed', 'thermal'] },
      { name: 'Werner State p=0.8', description: 'Werner state mixing Bell state with white noise', stateType: 'Mixed', qubitCount: 2, blochCoordinates: null, densityMatrix: { note: 'p*|Phi+><Phi+| + (1-p)/4 * I' }, purity: 0.7, entropy: 0.6, visualizationType: 'Density Matrix', status: 'active', category: 'Mixed Entangled', tags: ['werner', 'noisy'] },
      { name: 'Cluster State 4-qubit', description: 'Linear cluster state for measurement-based quantum computing', stateType: 'Entangled', qubitCount: 4, blochCoordinates: null, densityMatrix: { note: '16x16 density matrix' }, purity: 1.0, entropy: 1.0, visualizationType: 'Graph State', status: 'active', category: 'Graph State', tags: ['cluster', 'mbqc'] },
      { name: 'Graph State Ring', description: 'Ring graph state with periodic boundary conditions', stateType: 'Entangled', qubitCount: 5, blochCoordinates: null, densityMatrix: { note: '32x32 density matrix' }, purity: 1.0, entropy: 1.0, visualizationType: 'Graph State', status: 'active', category: 'Graph State', tags: ['graph', 'ring'] },
    ]);
    console.log('State Visualizations seeded.');

    // ── 9. Entanglement Analyses (15) ──
    await EntanglementAnalysis.bulkCreate([
      { name: 'Bell Pair EPR', description: 'Standard Einstein-Podolsky-Rosen Bell pair analysis', entanglementType: 'Bipartite', qubitPairs: { pairs: [[0, 1]] }, concurrence: 1.0, bellStateType: 'Phi+', schmidtDecomposition: { coefficients: [0.707, 0.707] }, entanglementWitness: 'CHSH S=2.828', applications: 'Quantum teleportation, superdense coding', status: 'active', category: 'Bipartite', tags: ['epr', 'bell'] },
      { name: 'GHZ Entanglement 5Q', description: 'Five-qubit GHZ state genuine multipartite entanglement', entanglementType: 'Multipartite GHZ', qubitPairs: { pairs: [[0,1],[0,2],[0,3],[0,4]] }, concurrence: 1.0, bellStateType: 'GHZ', schmidtDecomposition: { coefficients: [0.707, 0.707] }, entanglementWitness: 'Mermin inequality', applications: 'Quantum secret sharing, metrology', status: 'active', category: 'Multipartite', tags: ['ghz', 'genuine'] },
      { name: 'W-State Entanglement', description: 'Three-qubit W state with robust bipartite entanglement', entanglementType: 'W-State', qubitPairs: { pairs: [[0,1],[0,2],[1,2]] }, concurrence: 0.667, bellStateType: 'W', schmidtDecomposition: { coefficients: [0.816, 0.577] }, entanglementWitness: 'W witness operator', applications: 'Quantum networks, robust quantum memory', status: 'active', category: 'Multipartite', tags: ['w-state', 'robust'] },
      { name: 'Cluster State Linear', description: 'Linear cluster state entanglement for MBQC', entanglementType: 'Cluster', qubitPairs: { pairs: [[0,1],[1,2],[2,3]] }, concurrence: 0.5, bellStateType: 'Cluster', schmidtDecomposition: { coefficients: [0.854, 0.354, 0.354, 0.146] }, entanglementWitness: 'Stabilizer witness', applications: 'Measurement-based quantum computing', status: 'active', category: 'Graph', tags: ['cluster', 'mbqc'] },
      { name: 'Graph State 2D Lattice', description: '2D lattice graph state for topological MBQC', entanglementType: 'Graph', qubitPairs: { pairs: [[0,1],[1,2],[3,4],[0,3],[1,4]] }, concurrence: 0.5, bellStateType: 'Graph', schmidtDecomposition: { note: 'Multi-partition' }, entanglementWitness: 'Graph state witness', applications: 'Fault-tolerant MBQC', status: 'active', category: 'Graph', tags: ['graph', '2d'] },
      { name: 'EPR Pair Noisy', description: 'Noisy EPR pair under depolarizing noise', entanglementType: 'Bipartite Mixed', qubitPairs: { pairs: [[0,1]] }, concurrence: 0.85, bellStateType: 'Phi+ (noisy)', schmidtDecomposition: { coefficients: [0.68, 0.32] }, entanglementWitness: 'CHSH S=2.6', applications: 'Entanglement distillation study', status: 'active', category: 'Noisy', tags: ['noisy', 'distillation'] },
      { name: 'Singlet State Analysis', description: 'Spin singlet (|01> - |10>)/sqrt(2) anti-correlation study', entanglementType: 'Bipartite', qubitPairs: { pairs: [[0,1]] }, concurrence: 1.0, bellStateType: 'Psi-', schmidtDecomposition: { coefficients: [0.707, 0.707] }, entanglementWitness: 'CHSH S=2.828', applications: 'Quantum key distribution', status: 'active', category: 'Bipartite', tags: ['singlet', 'anti-correlated'] },
      { name: 'Triplet State Analysis', description: 'Spin triplet state characterization', entanglementType: 'Bipartite', qubitPairs: { pairs: [[0,1]] }, concurrence: 1.0, bellStateType: 'Psi+', schmidtDecomposition: { coefficients: [0.707, 0.707] }, entanglementWitness: 'CHSH violation', applications: 'Spin physics', status: 'active', category: 'Bipartite', tags: ['triplet', 'spin'] },
      { name: 'Multipartite 8-qubit', description: 'Eight-qubit multipartite entanglement characterization', entanglementType: 'Multipartite', qubitPairs: { pairs: 'all-to-all' }, concurrence: 0.75, bellStateType: 'AME', schmidtDecomposition: { note: 'Multiple bipartitions' }, entanglementWitness: 'GME witness', applications: 'Quantum error correction', status: 'experimental', category: 'Multipartite', tags: ['multipartite', 'large'] },
      { name: 'Bound Entanglement PPT', description: 'PPT bound entangled state that cannot be distilled', entanglementType: 'Bound', qubitPairs: { pairs: [[0,1],[2,3]] }, concurrence: 0.0, bellStateType: 'N/A', schmidtDecomposition: { note: 'PPT but entangled' }, entanglementWitness: 'Entanglement witness', applications: 'Theoretical interest, activation protocols', status: 'experimental', category: 'Bound', tags: ['bound', 'ppt'] },
      { name: 'Distillable Entanglement', description: 'Protocol for distilling maximally entangled pairs', entanglementType: 'Distillable', qubitPairs: { pairs: [[0,1]] }, concurrence: 0.95, bellStateType: 'Phi+ distilled', schmidtDecomposition: { coefficients: [0.69, 0.31] }, entanglementWitness: 'Distillation rate', applications: 'Long-distance quantum communication', status: 'active', category: 'Distillation', tags: ['distillable', 'protocol'] },
      { name: 'PPT Entangled Horodecki', description: 'Horodecki 3x3 PPT entangled state study', entanglementType: 'PPT Entangled', qubitPairs: { pairs: [[0,1]] }, concurrence: 0.0, bellStateType: 'N/A', schmidtDecomposition: { note: 'Qutrit state' }, entanglementWitness: 'Decomposable witness', applications: 'Entanglement theory', status: 'experimental', category: 'Theoretical', tags: ['horodecki', 'qutrit'] },
      { name: 'Hyperentangled Photon Pair', description: 'Photon pair entangled in polarization and orbital angular momentum', entanglementType: 'Hyperentanglement', qubitPairs: { pairs: [[0,1]], dof: ['polarization', 'OAM'] }, concurrence: 0.98, bellStateType: 'Hyper-Bell', schmidtDecomposition: { coefficients: [0.707, 0.707] }, entanglementWitness: 'Hyper-CHSH', applications: 'Dense coding, improved teleportation', status: 'active', category: 'Photonic', tags: ['hyper', 'photonic'] },
      { name: 'Time-bin Entanglement', description: 'Fiber-based time-bin entangled photon pairs', entanglementType: 'Time-bin', qubitPairs: { pairs: [[0,1]], encoding: 'time-bin' }, concurrence: 0.96, bellStateType: 'Time-bin Bell', schmidtDecomposition: { coefficients: [0.707, 0.707] }, entanglementWitness: 'Franson interference', applications: 'Fiber QKD, long-distance', status: 'active', category: 'Photonic', tags: ['time-bin', 'fiber'] },
      { name: 'OAM Entanglement', description: 'Orbital angular momentum entangled photon pairs', entanglementType: 'OAM', qubitPairs: { pairs: [[0,1]], encoding: 'OAM modes' }, concurrence: 0.92, bellStateType: 'OAM Bell', schmidtDecomposition: { coefficients: [0.707, 0.707] }, entanglementWitness: 'OAM CHSH', applications: 'High-dimensional QKD', status: 'experimental', category: 'Photonic', tags: ['oam', 'high-dimensional'] },
    ]);
    console.log('Entanglement Analyses seeded.');

    // ── 10. Quantum ML (15) ──
    await QuantumML.bulkCreate([
      { name: 'QNN Binary Classifier', description: 'Quantum neural network for binary classification on Iris dataset', modelType: 'QNN', datasetSize: 150, featureMap: 'ZZFeatureMap', ansatzType: 'RealAmplitudes', layers: 4, trainingAccuracy: 0.96, classicalBaseline: 0.94, quantumAdvantage: 'Marginal 2% improvement', status: 'completed', category: 'Classification', tags: ['qnn', 'iris'] },
      { name: 'Quantum SVM Kernel', description: 'Quantum kernel SVM using fidelity quantum kernel', modelType: 'QSVM', datasetSize: 500, featureMap: 'PauliFeatureMap', ansatzType: 'N/A', layers: 2, trainingAccuracy: 0.93, classicalBaseline: 0.91, quantumAdvantage: 'Better on specific data distributions', status: 'active', category: 'Classification', tags: ['qsvm', 'kernel'] },
      { name: 'VQC Multiclass', description: 'Variational quantum classifier for multi-class problems', modelType: 'VQC', datasetSize: 1000, featureMap: 'AmplitudeEncoding', ansatzType: 'EfficientSU2', layers: 6, trainingAccuracy: 0.89, classicalBaseline: 0.92, quantumAdvantage: 'Not yet demonstrated', status: 'training', category: 'Classification', tags: ['vqc', 'multiclass'] },
      { name: 'Quantum Boltzmann Machine', description: 'Quantum-enhanced Boltzmann machine for generative modeling', modelType: 'QBM', datasetSize: 5000, featureMap: 'N/A', ansatzType: 'Transverse Ising', layers: 8, trainingAccuracy: 0.85, classicalBaseline: 0.83, quantumAdvantage: 'Faster training convergence', status: 'experimental', category: 'Generative', tags: ['qbm', 'generative'] },
      { name: 'Quantum GAN', description: 'Quantum generative adversarial network for distribution loading', modelType: 'QGAN', datasetSize: 2000, featureMap: 'N/A', ansatzType: 'Hardware Efficient', layers: 5, trainingAccuracy: 0.88, classicalBaseline: 0.90, quantumAdvantage: 'Exponential state space', status: 'experimental', category: 'Generative', tags: ['qgan', 'adversarial'] },
      { name: 'Quantum RL CartPole', description: 'Quantum reinforcement learning agent for CartPole environment', modelType: 'QRL', datasetSize: 10000, featureMap: 'AngleEncoding', ansatzType: 'StronglyEntangling', layers: 3, trainingAccuracy: 0.92, classicalBaseline: 0.95, quantumAdvantage: 'Fewer parameters needed', status: 'active', category: 'Reinforcement', tags: ['qrl', 'cartpole'] },
      { name: 'Quantum Kernel Estimator', description: 'Quantum kernel estimation for non-linear classification', modelType: 'Quantum Kernel', datasetSize: 800, featureMap: 'ZFeatureMap', ansatzType: 'N/A', layers: 3, trainingAccuracy: 0.94, classicalBaseline: 0.89, quantumAdvantage: 'Exponential kernel dimension', status: 'active', category: 'Kernel Methods', tags: ['kernel', 'non-linear'] },
      { name: 'QAOA ML Combinatorial', description: 'QAOA-based approach for combinatorial ML problems', modelType: 'QAOA', datasetSize: 200, featureMap: 'Problem-specific', ansatzType: 'QAOA Mixer', layers: 5, trainingAccuracy: 0.78, classicalBaseline: 0.75, quantumAdvantage: 'Better optimization landscape', status: 'experimental', category: 'Optimization', tags: ['qaoa', 'combinatorial'] },
      { name: 'Quantum Transfer Learning', description: 'Pre-trained quantum feature extractor with classical head', modelType: 'Transfer', datasetSize: 3000, featureMap: 'Pre-trained circuit', ansatzType: 'ResNet + VQC', layers: 4, trainingAccuracy: 0.91, classicalBaseline: 0.93, quantumAdvantage: 'Reduced training data needed', status: 'active', category: 'Transfer', tags: ['transfer', 'hybrid'] },
      { name: 'Quantum Autoencoder', description: 'Quantum autoencoder for quantum data compression', modelType: 'Autoencoder', datasetSize: 500, featureMap: 'N/A', ansatzType: 'Parameterized', layers: 6, trainingAccuracy: 0.87, classicalBaseline: 0.82, quantumAdvantage: 'Native quantum compression', status: 'active', category: 'Compression', tags: ['autoencoder', 'compression'] },
      { name: 'Quantum PCA', description: 'Quantum principal component analysis for dimensionality reduction', modelType: 'QPCA', datasetSize: 1000, featureMap: 'Density matrix', ansatzType: 'N/A', layers: 0, trainingAccuracy: 0.95, classicalBaseline: 0.95, quantumAdvantage: 'Exponential speedup for low-rank', status: 'active', category: 'Dimensionality', tags: ['qpca', 'reduction'] },
      { name: 'Quantum CNN Image', description: 'Quantum convolutional neural network for image classification', modelType: 'QCNN', datasetSize: 5000, featureMap: 'Amplitude Encoding', ansatzType: 'Convolutional + Pooling', layers: 8, trainingAccuracy: 0.86, classicalBaseline: 0.94, quantumAdvantage: 'Fewer parameters', status: 'training', category: 'Vision', tags: ['qcnn', 'image'] },
      { name: 'Quantum Reservoir Computing', description: 'Quantum reservoir for temporal data processing', modelType: 'Reservoir', datasetSize: 2000, featureMap: 'Time-series encoding', ansatzType: 'Random circuit', layers: 10, trainingAccuracy: 0.90, classicalBaseline: 0.87, quantumAdvantage: 'Richer dynamics', status: 'experimental', category: 'Temporal', tags: ['reservoir', 'temporal'] },
      { name: 'Quantum Federated Learning', description: 'Privacy-preserving federated quantum machine learning', modelType: 'Federated', datasetSize: 10000, featureMap: 'Distributed encoding', ansatzType: 'EfficientSU2', layers: 4, trainingAccuracy: 0.88, classicalBaseline: 0.89, quantumAdvantage: 'Quantum secure aggregation', status: 'experimental', category: 'Privacy', tags: ['federated', 'privacy'] },
      { name: 'VQE-ML Hybrid', description: 'VQE-inspired variational circuit for regression tasks', modelType: 'VQE-ML', datasetSize: 800, featureMap: 'PauliFeatureMap', ansatzType: 'UCCSD-inspired', layers: 5, trainingAccuracy: 0.91, classicalBaseline: 0.88, quantumAdvantage: 'Better expressibility', status: 'active', category: 'Regression', tags: ['vqe', 'regression'] },
    ]);
    console.log('Quantum ML seeded.');

    // ── 11. Research Papers (15) ──
    await ResearchPaper.bulkCreate([
      { title: 'Quantum Supremacy Using a Programmable Superconducting Processor', authors: 'Arute F, Arya K, Babbush R, et al.', abstract: 'Demonstrates quantum computational advantage using a 53-qubit Sycamore processor performing random circuit sampling in 200 seconds.', journal: 'Nature', year: 2019, doi: '10.1038/s41586-019-1666-5', citations: 5200, researchArea: 'Quantum Computing', keyFindings: 'First demonstration of quantum supremacy, 53-qubit processor', status: 'active', category: 'Milestone', tags: ['supremacy', 'google'] },
      { title: 'Quantum Error Correction with Surface Codes Below Threshold', authors: 'Google Quantum AI', abstract: 'Demonstrates that increasing surface code distance reduces logical error rates, showing below-threshold operation.', journal: 'Nature', year: 2023, doi: '10.1038/s41586-022-05434-1', citations: 1800, researchArea: 'Error Correction', keyFindings: 'Surface code below threshold, exponential error suppression', status: 'active', category: 'Error Correction', tags: ['surface-code', 'threshold'] },
      { title: 'Variational Quantum Eigensolver for Electronic Structure', authors: 'Peruzzo A, McClean J, Shadbolt P, et al.', abstract: 'First experimental demonstration of VQE algorithm for computing molecular ground state energies on a photonic quantum processor.', journal: 'Nature Communications', year: 2014, doi: '10.1038/ncomms5213', citations: 3100, researchArea: 'Quantum Chemistry', keyFindings: 'VQE proof of concept, hybrid quantum-classical', status: 'active', category: 'Algorithms', tags: ['vqe', 'chemistry'] },
      { title: 'Quantum Approximate Optimization Algorithm', authors: 'Farhi E, Goldstone J, Gutmann S', abstract: 'Introduces QAOA, a quantum algorithm for approximate combinatorial optimization problems.', journal: 'arXiv:1411.4028', year: 2014, doi: 'arXiv:1411.4028', citations: 4500, researchArea: 'Algorithms', keyFindings: 'QAOA framework, combinatorial optimization', status: 'active', category: 'Algorithms', tags: ['qaoa', 'optimization'] },
      { title: 'Quantum Machine Learning: What Quantum Computing Means to Data Mining', authors: 'Wittek P', abstract: 'Comprehensive review of quantum machine learning algorithms and their potential advantages over classical methods.', journal: 'Academic Press', year: 2014, doi: '10.1016/C2013-0-19170-2', citations: 2200, researchArea: 'Quantum ML', keyFindings: 'QML taxonomy, speedup analysis', status: 'active', category: 'Review', tags: ['qml', 'review'] },
      { title: 'Quantum Computational Advantage with Trapped Ions', authors: 'Monroe C, Kim J', abstract: 'Review of trapped-ion quantum computing advances and path toward quantum advantage.', journal: 'Reviews of Modern Physics', year: 2021, doi: '10.1103/RevModPhys.93.025001', citations: 900, researchArea: 'Hardware', keyFindings: 'Ion trap progress, all-to-all connectivity advantages', status: 'active', category: 'Hardware', tags: ['ion-trap', 'review'] },
      { title: 'Noise-Resilient Quantum Circuits with Mid-Circuit Measurements', authors: 'Gupta R, Sundaresan N, et al.', abstract: 'Demonstrates practical quantum error mitigation using mid-circuit measurements and feed-forward.', journal: 'Physical Review X', year: 2024, doi: '10.1103/PhysRevX.14.021001', citations: 350, researchArea: 'Error Mitigation', keyFindings: 'Feed-forward error correction, mid-circuit measurement', status: 'active', category: 'Error Mitigation', tags: ['mid-circuit', 'feed-forward'] },
      { title: 'Quantum Networks with Entanglement Distribution', authors: 'Wehner S, Elkouss D, Hanson R', abstract: 'Roadmap for developing quantum internet from entanglement distribution to full quantum networks.', journal: 'Science', year: 2018, doi: '10.1126/science.aam9288', citations: 2800, researchArea: 'Quantum Networks', keyFindings: 'Quantum internet stages, entanglement distribution', status: 'active', category: 'Networks', tags: ['quantum-internet', 'roadmap'] },
      { title: 'Barren Plateaus in Quantum Neural Network Training', authors: 'McClean J, Boixo S, Smelyanskiy V, et al.', abstract: 'Identifies the barren plateau problem in variational quantum algorithm training landscapes.', journal: 'Nature Communications', year: 2018, doi: '10.1038/s41467-018-07090-4', citations: 2100, researchArea: 'Variational Algorithms', keyFindings: 'Barren plateau identification, trainability issues', status: 'active', category: 'Theoretical', tags: ['barren-plateau', 'vqa'] },
      { title: 'Quantum Computing in the NISQ Era and Beyond', authors: 'Preskill J', abstract: 'Defines the NISQ era and discusses prospects for near-term quantum advantage.', journal: 'Quantum', year: 2018, doi: '10.22331/q-2018-08-06-79', citations: 6500, researchArea: 'General', keyFindings: 'NISQ era definition, noisy intermediate-scale quantum', status: 'active', category: 'Perspective', tags: ['nisq', 'preskill'] },
      { title: 'Logical Qubit Operations with Neutral Atoms', authors: 'Bluvstein D, Evered S, et al.', abstract: 'Demonstrates fault-tolerant quantum operations on logical qubits using neutral atom arrays.', journal: 'Nature', year: 2024, doi: '10.1038/s41586-023-06927-3', citations: 600, researchArea: 'Fault Tolerance', keyFindings: 'Logical qubit operations, 48 logical qubits', status: 'active', category: 'Milestone', tags: ['neutral-atom', 'logical'] },
      { title: 'Exponential Quantum Speedup in Simulating Coupled Classical Oscillators', authors: 'Babbush R, Berry D, et al.', abstract: 'Proves exponential quantum speedup for simulating systems of coupled harmonic oscillators.', journal: 'Physical Review X', year: 2023, doi: '10.1103/PhysRevX.13.041041', citations: 250, researchArea: 'Quantum Simulation', keyFindings: 'Proven exponential speedup, BQP-complete problem', status: 'active', category: 'Theory', tags: ['speedup', 'simulation'] },
      { title: 'Quantum Key Distribution: A Comprehensive Review', authors: 'Xu F, Ma X, Zhang Q, et al.', abstract: 'Comprehensive review of quantum key distribution protocols, implementations, and security proofs.', journal: 'Reviews of Modern Physics', year: 2020, doi: '10.1103/RevModPhys.92.025002', citations: 1500, researchArea: 'Cryptography', keyFindings: 'QKD protocol comparison, practical security analysis', status: 'active', category: 'Cryptography', tags: ['qkd', 'review'] },
      { title: 'Quantum Error Mitigation Techniques for NISQ Devices', authors: 'Cai Z, Babbush R, et al.', abstract: 'Systematic review of quantum error mitigation techniques including ZNE, PEC, and CDR.', journal: 'Reviews of Modern Physics', year: 2023, doi: '10.1103/RevModPhys.95.045005', citations: 800, researchArea: 'Error Mitigation', keyFindings: 'Error mitigation taxonomy, practical guidelines', status: 'active', category: 'Error Mitigation', tags: ['mitigation', 'nisq'] },
      { title: 'Fault-Tolerant Quantum Computation by Anyons', authors: 'Kitaev A', abstract: 'Foundational paper on topological quantum computation using anyonic systems.', journal: 'Annals of Physics', year: 2003, doi: '10.1016/S0003-4916(02)00018-0', citations: 7200, researchArea: 'Topological QC', keyFindings: 'Topological quantum computation, anyon model', status: 'active', category: 'Foundational', tags: ['topological', 'kitaev'] },
    ]);
    console.log('Research Papers seeded.');

    // ── 12. Quantum Protocols (15) ──
    await QuantumProtocol.bulkCreate([
      { name: 'BB84 Protocol', description: 'First quantum key distribution protocol using four polarization states', protocolType: 'QKD', securityLevel: 'Information-theoretic', keyRate: '1 Mbps @ 10km', distance: '100 km fiber', resourceRequirements: 'Single photon source, 2 bases', implementation: 'Commercial (ID Quantique)', verificationMethod: 'Sifting + Error estimation', status: 'production', category: 'QKD', tags: ['bb84', 'commercial'] },
      { name: 'E91 Protocol', description: 'Entanglement-based QKD using Bell inequality violation', protocolType: 'QKD', securityLevel: 'Information-theoretic', keyRate: '100 kbps @ 10km', distance: '50 km fiber', resourceRequirements: 'Entangled photon source', implementation: 'Experimental', verificationMethod: 'CHSH inequality test', status: 'experimental', category: 'QKD', tags: ['e91', 'entanglement'] },
      { name: 'BBM92 Protocol', description: 'Entanglement-based variant of BB84 without basis reconciliation', protocolType: 'QKD', securityLevel: 'Information-theoretic', keyRate: '500 kbps @ 10km', distance: '80 km fiber', resourceRequirements: 'Entangled photon pair source', implementation: 'Lab demonstrated', verificationMethod: 'Coincidence detection', status: 'experimental', category: 'QKD', tags: ['bbm92', 'simplified'] },
      { name: 'SARG04 Protocol', description: 'QKD protocol robust against photon number splitting attacks', protocolType: 'QKD', securityLevel: 'PNS-resistant', keyRate: '200 kbps @ 10km', distance: '60 km fiber', resourceRequirements: 'Weak coherent pulses', implementation: 'Lab demonstrated', verificationMethod: 'Parameter estimation', status: 'experimental', category: 'QKD', tags: ['sarg04', 'pns-resistant'] },
      { name: 'COW Protocol', description: 'Coherent one-way QKD with simple implementation', protocolType: 'QKD', securityLevel: 'Practical', keyRate: '1 Mbps @ 25km', distance: '150 km fiber', resourceRequirements: 'Coherent laser, time-bin', implementation: 'Commercial (ID Quantique)', verificationMethod: 'Monitoring line visibility', status: 'production', category: 'QKD', tags: ['cow', 'coherent'] },
      { name: 'DPS Protocol', description: 'Differential phase shift QKD for high-speed key generation', protocolType: 'QKD', securityLevel: 'Practical', keyRate: '2 Mbps @ 10km', distance: '100 km fiber', resourceRequirements: 'Coherent pulses, interferometer', implementation: 'NTT deployed', verificationMethod: 'Bit error rate monitoring', status: 'production', category: 'QKD', tags: ['dps', 'high-speed'] },
      { name: 'MDI-QKD', description: 'Measurement-device-independent QKD closing all detector side channels', protocolType: 'QKD', securityLevel: 'Device-independent (measurement)', keyRate: '100 kbps @ 10km', distance: '400 km fiber', resourceRequirements: 'Two sources, untrusted relay', implementation: 'Lab demonstrated', verificationMethod: 'Bell state measurement', status: 'experimental', category: 'QKD', tags: ['mdi', 'secure'] },
      { name: 'Twin-Field QKD', description: 'QKD protocol breaking rate-distance limit using single-photon interference', protocolType: 'QKD', securityLevel: 'Information-theoretic', keyRate: '10 kbps @ 500km', distance: '830 km fiber', resourceRequirements: 'Phase-locked lasers', implementation: 'Record distance', verificationMethod: 'Phase randomization', status: 'experimental', category: 'QKD', tags: ['twin-field', 'long-distance'] },
      { name: 'Quantum Teleportation Standard', description: 'Standard quantum state teleportation protocol', protocolType: 'Teleportation', securityLevel: 'N/A', keyRate: 'N/A', distance: '1400 km (satellite)', resourceRequirements: 'Shared Bell pair, 2 cbits', implementation: 'Satellite demonstrated', verificationMethod: 'State tomography', status: 'experimental', category: 'Communication', tags: ['teleportation', 'satellite'] },
      { name: 'Quantum Dense Coding', description: 'Send 2 classical bits using 1 qubit with shared entanglement', protocolType: 'Communication', securityLevel: 'N/A', keyRate: '2 bits/qubit', distance: 'Lab scale', resourceRequirements: 'Shared Bell pair', implementation: 'Lab demonstrated', verificationMethod: 'Bell measurement', status: 'experimental', category: 'Communication', tags: ['dense-coding', 'superdense'] },
      { name: 'Quantum Secret Sharing', description: 'Distribute secret among n parties requiring threshold to reconstruct', protocolType: 'Multi-party', securityLevel: 'Information-theoretic', keyRate: '50 kbps shared', distance: '20 km per link', resourceRequirements: 'GHZ states', implementation: 'Lab demonstrated', verificationMethod: 'Threshold verification', status: 'experimental', category: 'Multi-party', tags: ['secret-sharing', 'threshold'] },
      { name: 'B92 Protocol', description: 'Simplified QKD using only two non-orthogonal states', protocolType: 'QKD', securityLevel: 'Information-theoretic', keyRate: '500 kbps @ 10km', distance: '30 km fiber', resourceRequirements: 'Single photon, 2 states', implementation: 'Lab demonstrated', verificationMethod: 'Error rate estimation', status: 'active', category: 'QKD', tags: ['b92', 'simplified'] },
      { name: 'Decoy State Protocol', description: 'Multi-intensity decoy state method for practical BB84', protocolType: 'QKD Enhancement', securityLevel: 'PNS-immune', keyRate: '1 Mbps @ 50km', distance: '200 km fiber', resourceRequirements: 'Variable intensity source', implementation: 'Commercial standard', verificationMethod: 'Decoy analysis', status: 'production', category: 'QKD', tags: ['decoy', 'practical'] },
      { name: 'CV-QKD Gaussian', description: 'Continuous-variable QKD using Gaussian modulation of coherent states', protocolType: 'QKD', securityLevel: 'Composable', keyRate: '5 Mbps @ 25km', distance: '100 km fiber', resourceRequirements: 'Homodyne/heterodyne detector', implementation: 'Commercial (Toshiba)', verificationMethod: 'Covariance matrix analysis', status: 'production', category: 'CV-QKD', tags: ['cv-qkd', 'gaussian'] },
      { name: 'DI-QKD', description: 'Fully device-independent QKD based on Bell inequality violation', protocolType: 'QKD', securityLevel: 'Fully device-independent', keyRate: '1 bps (current)', distance: '1 m (current)', resourceRequirements: 'Loophole-free Bell test', implementation: 'First demonstration 2022', verificationMethod: 'CHSH violation', status: 'experimental', category: 'QKD', tags: ['di-qkd', 'device-independent'] },
    ]);
    console.log('Quantum Protocols seeded.');

    // ── 13. Hardware Profiles (15) ──
    await HardwareProfile.bulkCreate([
      { name: 'IBM Eagle (ibm_brisbane)', description: '127-qubit heavy-hex topology processor', manufacturer: 'IBM', qubitCount: 127, qubitType: 'Transmon', connectivity: 'Heavy-hex', gateSet: 'ECR, Rz, X, SX', t1Time: '200 us', t2Time: '150 us', gateError: 0.003, status: 'active', category: 'Cloud', tags: ['ibm', 'eagle'] },
      { name: 'IBM Condor', description: '1121-qubit processor for utility-scale quantum computing', manufacturer: 'IBM', qubitCount: 1121, qubitType: 'Transmon', connectivity: 'Heavy-hex', gateSet: 'ECR, Rz, X, SX', t1Time: '180 us', t2Time: '120 us', gateError: 0.005, status: 'active', category: 'Cloud', tags: ['ibm', 'condor'] },
      { name: 'Google Sycamore', description: '53-qubit processor that demonstrated quantum supremacy', manufacturer: 'Google', qubitCount: 53, qubitType: 'Transmon', connectivity: 'Grid (2D)', gateSet: 'iSWAP, Rz, sqrt(X)', t1Time: '15 us', t2Time: '12 us', gateError: 0.006, status: 'active', category: 'Research', tags: ['google', 'sycamore'] },
      { name: 'IonQ Forte Enterprise', description: '36-qubit trapped-ion system with all-to-all connectivity', manufacturer: 'IonQ', qubitCount: 36, qubitType: 'Trapped Ion (Yb)', connectivity: 'All-to-all', gateSet: 'GPi, GPi2, MS', t1Time: '> 10 s', t2Time: '1 s', gateError: 0.002, status: 'active', category: 'Cloud', tags: ['ionq', 'forte'] },
      { name: 'Quantinuum H2', description: '56-qubit trapped-ion QCCD architecture processor', manufacturer: 'Quantinuum', qubitCount: 56, qubitType: 'Trapped Ion (Ba)', connectivity: 'All-to-all (QCCD)', gateSet: 'Rz, ZZ, arbitrary 1Q', t1Time: '> 10 s', t2Time: '3 s', gateError: 0.001, status: 'active', category: 'Cloud', tags: ['quantinuum', 'h2'] },
      { name: 'Rigetti Ankaa-3', description: '84-qubit tunable coupler superconducting processor', manufacturer: 'Rigetti', qubitCount: 84, qubitType: 'Transmon', connectivity: 'Square lattice', gateSet: 'CZ, Rz, Rx', t1Time: '25 us', t2Time: '15 us', gateError: 0.005, status: 'active', category: 'Cloud', tags: ['rigetti', 'ankaa'] },
      { name: 'Xanadu Borealis', description: '216-squeezed-mode photonic quantum computer for GBS', manufacturer: 'Xanadu', qubitCount: 216, qubitType: 'Photonic (squeezed)', connectivity: 'Programmable interferometer', gateSet: 'Beam splitter, Phase shift', t1Time: 'N/A', t2Time: 'N/A', gateError: 0.01, status: 'active', category: 'Photonic', tags: ['xanadu', 'borealis'] },
      { name: 'QuEra Aquila', description: '256-atom neutral atom quantum computer', manufacturer: 'QuEra', qubitCount: 256, qubitType: 'Neutral Atom (Rb)', connectivity: 'Reconfigurable 2D array', gateSet: 'CZ, Rydberg blockade', t1Time: '5 s', t2Time: '1 s', gateError: 0.005, status: 'active', category: 'Neutral Atom', tags: ['quera', 'neutral-atom'] },
      { name: 'PsiQuantum Photonic System', description: 'Silicon photonic fault-tolerant quantum computer (in development)', manufacturer: 'PsiQuantum', qubitCount: 1000000, qubitType: 'Photonic (silicon)', connectivity: 'Fusion-based', gateSet: 'Fusion gates, GKP', t1Time: 'N/A', t2Time: 'N/A', gateError: 0.001, status: 'experimental', category: 'Photonic', tags: ['psiquantum', 'fault-tolerant'] },
      { name: 'D-Wave Advantage 5000Q', description: '5000+ qubit quantum annealer with Pegasus topology', manufacturer: 'D-Wave', qubitCount: 5627, qubitType: 'Flux Qubit', connectivity: 'Pegasus (15-connected)', gateSet: 'Annealing (not gate-based)', t1Time: '100 us', t2Time: '50 us', gateError: 0.05, status: 'active', category: 'Annealer', tags: ['dwave', 'annealer'] },
      { name: 'AQT Pine', description: '24-qubit trapped-ion system from Alpine Quantum Technologies', manufacturer: 'AQT', qubitCount: 24, qubitType: 'Trapped Ion (Ca)', connectivity: 'All-to-all', gateSet: 'MS, Rz, Ry', t1Time: '> 1 s', t2Time: '500 ms', gateError: 0.003, status: 'active', category: 'Cloud', tags: ['aqt', 'european'] },
      { name: 'OQC Lucy', description: '8-qubit superconducting Coaxmon processor', manufacturer: 'Oxford Quantum Circuits', qubitCount: 8, qubitType: 'Coaxmon', connectivity: 'Ring', gateSet: 'CZ, Rx, Rz', t1Time: '50 us', t2Time: '30 us', gateError: 0.008, status: 'active', category: 'Cloud', tags: ['oqc', 'coaxmon'] },
      { name: 'Pasqal Fresnel', description: '100-atom neutral atom processor with analog and digital modes', manufacturer: 'Pasqal', qubitCount: 100, qubitType: 'Neutral Atom (Rb)', connectivity: 'Configurable 2D/3D', gateSet: 'CZ, single-qubit rotations', t1Time: '3 s', t2Time: '500 ms', gateError: 0.005, status: 'active', category: 'Neutral Atom', tags: ['pasqal', 'analog'] },
      { name: 'Alice & Bob Cat Qubit', description: 'Bosonic cat qubit processor with exponential bit-flip suppression', manufacturer: 'Alice & Bob', qubitCount: 4, qubitType: 'Cat Qubit', connectivity: 'Bus cavity', gateSet: 'CNOT, Toffoli (bias-preserving)', t1Time: '1 ms (bit-flip)', t2Time: '100 us', gateError: 0.01, status: 'experimental', category: 'Bosonic', tags: ['cat-qubit', 'bosonic'] },
      { name: 'SpinQ Gemini Mini', description: 'Desktop 2-qubit NMR quantum computer for education', manufacturer: 'SpinQ', qubitCount: 2, qubitType: 'NMR', connectivity: 'All-to-all', gateSet: 'Universal 1Q and 2Q', t1Time: '1 s', t2Time: '500 ms', gateError: 0.02, status: 'active', category: 'Desktop', tags: ['spinq', 'education'] },
    ]);
    console.log('Hardware Profiles seeded.');

    // ── 14. Benchmark Tests (15) ──
    await BenchmarkTest.bulkCreate([
      { name: 'Quantum Volume 64 Test', description: 'QV=64 benchmark on IBM Eagle processor', benchmarkType: 'Quantum Volume', circuitDepth: 6, qubitCount: 6, quantumVolume: 64, clops: 15000, successRate: 0.72, executionTime: '120 sec', hardwareTarget: 'IBM Eagle', status: 'completed', category: 'Volume', tags: ['qv64', 'ibm'] },
      { name: 'Quantum Volume 128 Test', description: 'QV=128 benchmark on Quantinuum H1', benchmarkType: 'Quantum Volume', circuitDepth: 7, qubitCount: 7, quantumVolume: 128, clops: 25, successRate: 0.68, executionTime: '600 sec', hardwareTarget: 'Quantinuum H1', status: 'completed', category: 'Volume', tags: ['qv128', 'quantinuum'] },
      { name: 'Quantum Volume 256 Test', description: 'QV=256 benchmark on IonQ Forte', benchmarkType: 'Quantum Volume', circuitDepth: 8, qubitCount: 8, quantumVolume: 256, clops: 50, successRate: 0.67, executionTime: '900 sec', hardwareTarget: 'IonQ Forte', status: 'completed', category: 'Volume', tags: ['qv256', 'ionq'] },
      { name: 'Random Circuit Sampling 50Q', description: 'RCS benchmark for quantum advantage verification', benchmarkType: 'Random Circuit', circuitDepth: 20, qubitCount: 50, quantumVolume: null, clops: null, successRate: 0.002, executionTime: '200 sec', hardwareTarget: 'Google Sycamore', status: 'completed', category: 'Supremacy', tags: ['rcs', 'google'] },
      { name: 'Mirror Circuit Fidelity 20Q', description: 'Mirror circuit benchmark for error rate estimation', benchmarkType: 'Mirror Circuit', circuitDepth: 50, qubitCount: 20, quantumVolume: null, clops: null, successRate: 0.45, executionTime: '300 sec', hardwareTarget: 'IBM Eagle', status: 'completed', category: 'Fidelity', tags: ['mirror', 'fidelity'] },
      { name: 'Cross-Entropy Benchmark', description: 'XEB fidelity benchmark for random circuit sampling', benchmarkType: 'Cross-Entropy', circuitDepth: 20, qubitCount: 53, quantumVolume: null, clops: null, successRate: 0.002, executionTime: '200 sec', hardwareTarget: 'Google Sycamore', status: 'completed', category: 'Fidelity', tags: ['xeb', 'cross-entropy'] },
      { name: 'CLOPS Standard Measurement', description: 'Circuit Layer Operations Per Second throughput benchmark', benchmarkType: 'CLOPS', circuitDepth: 100, qubitCount: 100, quantumVolume: null, clops: 16000, successRate: null, executionTime: '60 sec', hardwareTarget: 'IBM Eagle', status: 'completed', category: 'Throughput', tags: ['clops', 'throughput'] },
      { name: 'VQE Energy Accuracy', description: 'Application benchmark: VQE accuracy for H2 molecule', benchmarkType: 'Application', circuitDepth: 20, qubitCount: 4, quantumVolume: null, clops: null, successRate: 0.99, executionTime: '300 sec', hardwareTarget: 'Quantinuum H1', status: 'completed', category: 'Application', tags: ['vqe', 'chemistry'] },
      { name: 'QAOA MaxCut Performance', description: 'Application benchmark: QAOA approximation ratio for random graphs', benchmarkType: 'Application', circuitDepth: 30, qubitCount: 16, quantumVolume: null, clops: null, successRate: 0.85, executionTime: '500 sec', hardwareTarget: 'IonQ Forte', status: 'completed', category: 'Application', tags: ['qaoa', 'maxcut'] },
      { name: 'Layer Fidelity 127Q', description: 'Per-layer fidelity measurement across full 127-qubit device', benchmarkType: 'Layer Fidelity', circuitDepth: 1, qubitCount: 127, quantumVolume: null, clops: null, successRate: 0.992, executionTime: '180 sec', hardwareTarget: 'IBM Eagle', status: 'completed', category: 'Fidelity', tags: ['layer', 'full-chip'] },
      { name: 'Single Qubit RB', description: 'Randomized benchmarking for single-qubit gate fidelity', benchmarkType: 'Gate Benchmark', circuitDepth: 200, qubitCount: 1, quantumVolume: null, clops: null, successRate: 0.9998, executionTime: '30 sec', hardwareTarget: 'Quantinuum H2', status: 'completed', category: 'Gate', tags: ['rb', 'single-qubit'] },
      { name: 'Readout Fidelity Test', description: 'State preparation and measurement fidelity benchmark', benchmarkType: 'Readout', circuitDepth: 0, qubitCount: 127, quantumVolume: null, clops: null, successRate: 0.985, executionTime: '60 sec', hardwareTarget: 'IBM Eagle', status: 'completed', category: 'Measurement', tags: ['readout', 'spam'] },
      { name: 'T1/T2 Coherence Survey', description: 'Systematic coherence time measurement across device', benchmarkType: 'Coherence', circuitDepth: 0, qubitCount: 127, quantumVolume: null, clops: null, successRate: null, executionTime: '600 sec', hardwareTarget: 'IBM Eagle', status: 'completed', category: 'Coherence', tags: ['t1', 't2'] },
      { name: 'Crosstalk Characterization', description: 'Simultaneous RB to characterize crosstalk errors', benchmarkType: 'Crosstalk', circuitDepth: 100, qubitCount: 20, quantumVolume: null, clops: null, successRate: 0.98, executionTime: '900 sec', hardwareTarget: 'Rigetti Ankaa', status: 'completed', category: 'Noise', tags: ['crosstalk', 'simultaneous-rb'] },
      { name: 'Full Stack Integration', description: 'End-to-end benchmark from circuit compilation to results', benchmarkType: 'Full Stack', circuitDepth: 50, qubitCount: 20, quantumVolume: 64, clops: 10000, successRate: 0.75, executionTime: '180 sec', hardwareTarget: 'IBM Eagle', status: 'completed', category: 'Integration', tags: ['full-stack', 'end-to-end'] },
    ]);
    console.log('Benchmark Tests seeded.');

    // ── 15. Learning Resources (15) ──
    await LearningResource.bulkCreate([
      { title: 'Qiskit Textbook: Learn Quantum Computing', description: 'Comprehensive interactive textbook covering quantum computing fundamentals using Qiskit', resourceType: 'Textbook', difficulty: 'Beginner', topic: 'Fundamentals', duration: '40 hours', prerequisites: 'Linear algebra basics', author: 'IBM Quantum', url: 'https://qiskit.org/learn', rating: 4.8, status: 'active', category: 'Course', tags: ['qiskit', 'ibm'] },
      { title: 'Quantum Computing: An Applied Approach (Hidary)', description: 'Practical textbook with code examples in Qiskit, Cirq, and Forest', resourceType: 'Textbook', difficulty: 'Intermediate', topic: 'Applied QC', duration: '60 hours', prerequisites: 'Basic quantum mechanics, Python', author: 'Jack Hidary', url: 'https://link.springer.com', rating: 4.5, status: 'active', category: 'Textbook', tags: ['textbook', 'applied'] },
      { title: 'Quantum Machine Learning (PennyLane)', description: 'Interactive tutorials on quantum machine learning using PennyLane', resourceType: 'Tutorial', difficulty: 'Intermediate', topic: 'Quantum ML', duration: '20 hours', prerequisites: 'ML basics, Python', author: 'Xanadu', url: 'https://pennylane.ai/qml/', rating: 4.7, status: 'active', category: 'Tutorial', tags: ['pennylane', 'qml'] },
      { title: 'Quantum Error Correction Course', description: 'Graduate-level course on quantum error correction theory and practice', resourceType: 'Course', difficulty: 'Advanced', topic: 'Error Correction', duration: '30 hours', prerequisites: 'Quantum information theory', author: 'MIT OpenCourseWare', url: 'https://ocw.mit.edu', rating: 4.6, status: 'active', category: 'Course', tags: ['error-correction', 'mit'] },
      { title: 'Quantum Computing Explained (video series)', description: 'Visual introduction to quantum computing concepts for beginners', resourceType: 'Video', difficulty: 'Beginner', topic: 'Fundamentals', duration: '8 hours', prerequisites: 'None', author: 'Domain of Science', url: 'https://youtube.com', rating: 4.4, status: 'active', category: 'Video', tags: ['video', 'visual'] },
      { title: 'Cirq Programming Workshop', description: 'Hands-on workshop for quantum circuit programming with Google Cirq', resourceType: 'Workshop', difficulty: 'Intermediate', topic: 'Programming', duration: '12 hours', prerequisites: 'Python, basic quantum concepts', author: 'Google Quantum AI', url: 'https://quantumai.google/cirq', rating: 4.5, status: 'active', category: 'Workshop', tags: ['cirq', 'google'] },
      { title: 'Nielsen & Chuang: Quantum Computation and QI', description: 'The definitive textbook on quantum computation and quantum information', resourceType: 'Textbook', difficulty: 'Advanced', topic: 'Theory', duration: '200 hours', prerequisites: 'Linear algebra, quantum mechanics', author: 'Nielsen & Chuang', url: 'https://cambridge.org', rating: 4.9, status: 'active', category: 'Textbook', tags: ['nielsen-chuang', 'bible'] },
      { title: 'Quantum Algorithms via Linear Algebra', description: 'Accessible introduction to quantum algorithms using linear algebra', resourceType: 'Textbook', difficulty: 'Beginner', topic: 'Algorithms', duration: '15 hours', prerequisites: 'Basic linear algebra', author: 'Lipton & Regan', url: 'https://mitpress.mit.edu', rating: 4.3, status: 'active', category: 'Textbook', tags: ['algorithms', 'accessible'] },
      { title: 'Quantum Cryptography Interactive Lab', description: 'Hands-on lab exercises for quantum key distribution protocols', resourceType: 'Interactive', difficulty: 'Intermediate', topic: 'Cryptography', duration: '10 hours', prerequisites: 'Classical cryptography basics', author: 'QuTech Academy', url: 'https://qutech.nl', rating: 4.6, status: 'active', category: 'Lab', tags: ['qkd', 'hands-on'] },
      { title: 'Quantum Hardware Engineering Seminar', description: 'Seminar series on building and characterizing quantum hardware', resourceType: 'Video', difficulty: 'Expert', topic: 'Hardware', duration: '25 hours', prerequisites: 'Condensed matter physics, EE', author: 'IQIM Caltech', url: 'https://iqim.caltech.edu', rating: 4.7, status: 'active', category: 'Seminar', tags: ['hardware', 'caltech'] },
      { title: 'Introduction to Quantum Computing (edX)', description: 'University-level MOOC on quantum computing fundamentals', resourceType: 'Course', difficulty: 'Beginner', topic: 'Fundamentals', duration: '35 hours', prerequisites: 'Basic math', author: 'TU Delft', url: 'https://edx.org', rating: 4.5, status: 'active', category: 'MOOC', tags: ['edx', 'mooc'] },
      { title: 'Quantum Simulation with Tensor Networks', description: 'Advanced tutorial on tensor network methods for quantum simulation', resourceType: 'Tutorial', difficulty: 'Expert', topic: 'Simulation', duration: '15 hours', prerequisites: 'Quantum many-body physics', author: 'Tensor Network Community', url: 'https://tensornetwork.org', rating: 4.4, status: 'active', category: 'Tutorial', tags: ['tensor', 'simulation'] },
      { title: 'Practical Quantum Computing for Developers', description: 'Developer-focused guide to quantum programming with multiple frameworks', resourceType: 'Course', difficulty: 'Intermediate', topic: 'Programming', duration: '20 hours', prerequisites: 'Software development experience', author: "O'Reilly", url: 'https://oreilly.com', rating: 4.3, status: 'active', category: 'Course', tags: ['developer', 'practical'] },
      { title: 'Quantum Noise and Error Mitigation Workshop', description: 'Hands-on workshop on characterizing and mitigating quantum noise', resourceType: 'Workshop', difficulty: 'Advanced', topic: 'Error Mitigation', duration: '8 hours', prerequisites: 'QC fundamentals, statistics', author: 'Qiskit Community', url: 'https://qiskit.org', rating: 4.6, status: 'active', category: 'Workshop', tags: ['noise', 'mitigation'] },
      { title: 'Quantum Computing Foundations (Brilliant)', description: 'Interactive problem-solving approach to quantum computing concepts', resourceType: 'Interactive', difficulty: 'Beginner', topic: 'Fundamentals', duration: '15 hours', prerequisites: 'High school math', author: 'Brilliant.org', url: 'https://brilliant.org', rating: 4.7, status: 'active', category: 'Interactive', tags: ['brilliant', 'interactive'] },
    ]);
    console.log('Learning Resources seeded.');

    console.log('\n✅ All seed data created successfully!');
    console.log('Seed admin created; credentials were supplied through the environment.');
    process.exit(0);
  } catch (error) {
    console.error('Seed failed:', error);
    process.exit(1);
  }
}

seed();
